services:
  warp-proxy:
    container_name: warp-proxy
    build:
      dockerfile: ./Dockerfile.warp
    ports:
      - 40000:40000
    restart: unless-stopped
    # environment:
    # - LICENSE=you-own-key
    logging:
      driver: json-file
      options:
        max-size: 1m
